# Generated by Django 5.2.4 on 2025-07-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
